require 'yaml'
require 'json'

class Default < Thor
  include Thor::Actions

  desc 'yaml2json [YAML_FILES]', 'Converts Swagger YAML to JSON'
  def yaml2json(pattern = 'source/**/swagger/*.yaml', *yaml_files)
    if yaml_files.empty?
      yaml_files = Dir[pattern]
    else
      yaml_files.unshift(pattern)
    end
    yaml_files.each do |swagger_yaml|
      name = File.basename(swagger_yaml, '.yaml')
      json_file = swagger_yaml.gsub('.yaml', '.json')
      add_file json_file do
        data = YAML.load(File.read(swagger_yaml))
        JSON.dump(data)
      end
    end
  end

  desc 'json2yaml [JSON_FILES]', 'Converts Swagger JSON to YAML'
  def json2yaml(pattern = 'source/**/swagger/*.json', *json_files)
    if json_files.empty?
      json_files = Dir[pattern]
    else
      json_files.unshift(pattern)
    end
    json_files.each do |swagger_json|
      name = File.basename(swagger_json, '.json')
      json_file = swagger_json.gsub('.json', '.yaml')
      add_file json_file do
        data = JSON.parse(File.read(swagger_json))
        YAML.dump(data)
      end
    end
  end
end
